on:
    push:
        branches: main
    pull_request:
        types: [closed]
        branches: main
    workflow_dispatch:
jobs:
    sync-template:
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        runs-on: ubuntu-latest
        steps:
            - name: Github App Token
              uses: actions/create-github-app-token@v1.10.2
              id: app-token
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.PRIVATE_KEY }}
                  owner: ${{ github.repository_owner }}
            - name: Queue
              uses: ahmadnassri/action-workflow-queue@v1.2
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Sync template
              uses: ahmadnassri/action-template-repository-sync@v2.6.3
              with:
                  github-token: ${{ steps.app-token.outputs.token }}
