on:
    push:
        branches: main
    workflow_dispatch:
jobs:
    sync-template:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Queue
              uses: ahmadnassri/action-workflow-queue@v1.2
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Sync template
              uses: ahmadnassri/action-template-repository-sync@v2.6.3
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
    sync-template-2:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Queue
              uses: ahmadnassri/action-workflow-queue@v1.2
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Sync template
              uses: ahmadnassri/action-template-repository-sync@v2.6.3
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
                  config: .github/template-sync-2.yml
